name: test-torch-2-8-composer
image: pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime

command: |
  apt update
  apt install git -y
  mkdir /mnist
  mkdir /mnist/datasets
  mkdir /checkpoints
  git clone https://github.com/srijitcn/test_mct 
  cd test_mct
  pip install -r requirements.txt 
  composer train.py

compute:
  gpus: 8
  cluster: r8z13p1

#enable watchdog
scheduling:
  retry_on_system_failure: True
  max_retries: 3