name: test-torch-2-8-composer
image: pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime

integrations:
- integration_type: git_repo
  git_repo: srijitcn/test_mct
  git_branch: main # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  mkdir /mnist
  mkdir /mnist/datasets
  mkdir /checkpoints
  pip install -r requirements.txt 
  composer train.py

compute:
  gpus: 8
  cluster: r8z13p1

#enable watchdog
scheduling:
  retry_on_system_failure: True
  max_retries: 3