name: test-torch-2-8-composer
image: mosaicml/pytorch:2.7.0_cu126-python3.12-ubuntu22.04

command: |
  apt update
  mkdir /mnist
  mkdir /mnist/datasets
  mkdir /checkpoints
  git clone https://github.com/srijitcn/test_mct 
  cd test_mct
  pip install -r requirements_1.txt 
  pip install -r requirements_2.txt 
  composer train.py

compute:
  gpus: 8
  cluster: r8z13p1

#enable watchdog
scheduling:
  retry_on_system_failure: True
  max_retries: 3