name: test-torch-2-8-composer-custom-docker
image: srijitnair254/composer_torch_2_8:latest

command: |
  mkdir /mnist
  mkdir /mnist/datasets
  mkdir /checkpoints
  git clone https://github.com/srijitcn/test_mct 
  cd test_mct
  python data.py
  composer train.py

compute:
  gpus: 8
  cluster: r8z13p1

#enable watchdog
scheduling:
  retry_on_system_failure: True
  max_retries: 3